os: windows
language: csharp
solution: src\SteamPathsLib.sln
services:
  - nuget
install:
  - nuget restore src\SteamPathsLib.sln
matrix:
  include:
    - name: Library Build
    script:
    - msbuild /p:Configuration=Release src\SteamPathsLib.sln
    
